sched/fair: fix compilation error due to undefined schedtune_initialized:
kernel/built-in.o: In function `normalize_energy':
kernel/sched/fair.c:6776: undefined reference to `schedtune_initialized'

Signed-off-by: zachariasmaladroit <zacharias.maladroit@gmail.com>